name: PullRequest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - trunk-merge/**


jobs:
  pr:
    name: Run Pull Request checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build
        run: sleep 2s

      - name: Check run forever file existence
        id: run_forever
        uses: andstor/file-existence-action@v1
        with:
          files: "test/run_forever.txt"

      - name: Run forever
        if: steps.run_forever.outputs.files_exists == 'true' && contains('trunk-merge', github.ref)
        run: sleep 180s
